01.11dz
fd1-53-17/ShustKristina pull request #3
Opened 2017-11-01 12:52 UTC by ShustKristina

@antonkulakov-it 
please review

2017-11-03 04:22 UTC, antonkulakov-it requested changes
заменить кавычки и минусы мнемониками
правильно использовать мнемоники

2017-11-03 04:22 UTC, antonkulakov-it commented on diary.html
> +    <p>&copy бородатый <a href="https://www.anekdot.ru/" title="самое смешное" target="_blank">анекдот</a></p>
в конце мнемоники должна стоять точка с запятой

2017-11-03 04:22 UTC, antonkulakov-it commented on diary.html
> +        <li><strong>Четверг. </strong>Под покровом ночи смогли снова засесть в доме лесника. Курим "Беломор".</li>
заменить кавычки и минусы мнемониками

2017-11-03 04:22 UTC, antonkulakov-it commented on vechno_student.html
> +    <p>Семь веков назад такой "пароль" появился у всех студентов. Не затерялась давняя студенческая песня в веках, передавалась от поколения к поколению. В 1781 году записал ее, предварительно обрабо
заменить кавычки и минусы мнемониками

2017-11-10 18:01 UTC, ShustKristina commented
@antonkulakov-it 
please review

2017-11-12 09:53 UTC, antonkulakov-it approved these changes

2017-11-12 09:53 UTC, merged